name: Run build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install pre-reqs
      run: apt install gcc libpng-dev make -y

    - name: compile
      run: make -j2

    - uses: actions/upload-artifact@v4
      with:
        name: optar_binaries
        path: |
          optar
          unoptar
          pgm2ps